# load all customers
GET http://localhost:8000/api/v1/customers
Accept: application/json

###

# load all customers with filter
GET http://localhost:8000/api/v1/customers?state[eq]=Idaho
Accept: application/json

###

# load all customers with their invoices
GET http://localhost:8000/api/v1/customers?includeInvoices=true
Accept: application/json

###

# load all invoices
GET http://localhost:8000/api/v1/invoices
Accept: application/json

###

# load all invoices with filter
GET http://localhost:8000/api/v1/invoices?amount[gte]=10000
Accept: application/json

###

# load all invoices with filter
GET http://localhost:8000/api/v1/invoices?customerId[eq]=1
Accept: application/json

###

# load all invoices with filter
GET http://localhost:8000/api/v1/invoices?amount[gte]=10000
Accept: application/json

###

# load one customers
GET http://localhost:8000/api/v1/customers/1
Accept: application/json

###

# load one customers whit invoices
GET http://localhost:8000/api/v1/customers/1?includeInvoices=true
Accept: application/json

###

# add customer
POST http://localhost:8000/api/v1/customers
Accept: application/json
Content-Type: application/json

{
  "name": "Mohsen",
  "type": "I",
  "email": "mohsen@mail.biz",
  "address": "208 Hansen Flats Apt. 16",
  "city": "New Peter",
  "state": "Idaho",
  "postalCode": "12345"
}

###

# Change customer
PUT http://localhost:8000/api/v1/customers/231
Accept: application/json
Content-Type: application/json

{
    "name": "Mohsen Shabanian",
    "type": "B",
    "email": "mohsen@mail.biz",
    "address": "4321 Hansen Flats Apt. 16",
    "city": "New Peter",
    "state": "Idaho",
    "postalCode": "12345"
}

###

# Change customer
PATCH http://localhost:8000/api/v1/customers/231
Accept: application/json
Content-Type: application/json

{
    "type": "I",
    "state": "Texas"
}

###

# store bulk invoice
POST http://localhost:8000/api/v1/invoices/bulk
Accept: application/json
Content-Type: application/json

[
    {
        "customerId": 1,
        "amount": "1001.00",
        "status": "B",
        "billedDate": "2019-07-14 14:41:32",
        "paidDate": null
    },
    {
        "customerId": 1,
        "amount": "1002.00",
        "status": "P",
        "billedDate": "2019-08-27 04:47:58",
        "paidDate": "2023-03-02 11:31:01"
    }
]

###

# load all customers with auth token
# read tokens from /setup
GET http://localhost:8000/api/v1/customers
Accept: application/json
Authorization:  Bearer O1P0bDi9RFCGJAZkculADXdbdYvoGNOzFe0YyVR8
